### ISSUE TITLE
Feature Request/Enhancement - Max Temp

### ISSUE THREAD

**Issue by lloydbayley** [denysdovhan/ha-check-weather#12]
How about a maximum temperature option for when it's too hot to do the activity?

**Comment by c11umw** [comment]
I was about to raise this as a request too :D

**Comment by denysdovhan** [comment]
Good point, the weather is hot at the moment 😅

You are welcome to contribute! It should be easy to implement.

**Comment by lloydbayley** [comment]
Well that's nice of you. I wasn't sure if you wanted PRs other than yourself and dependabot! :)
I shall have a look into this at some stage but I really ought to go to bed now. It's 1:18AM in Australia and I have a bad habit of starting things now and pushing through. I need to exercise some willpower! :)

**Comment by lloydbayley** [comment]
I see the issue is closed. Seems you got there first. Was looking forward to working on a HACS module but it seems I am not fast enough. It might have been nice to have a comment about you finding time to do it, but alas. I have removed my fork, repository, integration and all associations with it.

**Comment by denysdovhan** [comment]
You are welcome to contribute if you have any other ideas or fixes 🫶
