### ISSUE TITLE
expected float error when configuring from GUI

### ISSUE THREAD

**Issue by nepozs** [denysdovhan/ha-check-weather#18]
Custom component version 1.0.0

not possible to use values like 10.0 or 30.0 (they are autoconverted to 10 or 30 in GUI)
<img width="374" alt="expected_float_2024-07-20_22-33" src="https://github.com/user-attachments/assets/c11662d4-61d4-42f0-a4cb-dc4ff6a57fbf">

**Comment by Bigsmooth68** [comment]
Same issue here

**Comment by Bigsmooth68** [comment]
@nepozs if you add `.0` or whatever you want, it works. Of course, it should allow just int.
I am looking at the code.

**Comment by nepozs** [comment]
> if you add .0 or whatever you want, it works

Not possible to add .0 because 10.0 converts immediately to 10 
so workaround is 9.9 or 10.1 so it should be fixed…
